config/routes.rb
Rails.application.routes.draw do
   root 'welcome#index'

   get '/auth/:provider/callback', to: "sessions#create"
   delete '/logout', to: "sessions#destroy"

   resources :users do
     resources :potential_pairs, only: [:show, :index, :edit, :update]
     delete '/potential_pairs/remove', to: "potential_pairs#remove"
   end

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/language.rb
 class Language < ActiveRecord::Base
  has_many :user_languages
  has_many :users, through: :user_languages
 end

app/models/match.rb
class Match < ActiveRecord::Base
  belongs_to :first_accepter, class_name: :User, foreign_key: "first_accepter_id"
  belongs_to :second_accepter, class_name: :User, foreign_key: "second_accepter_id"

  def secondary_accepter
    User.find(second_accepter_id)
  end

  def self.make(current_user, pair_to_match)
    match = current_user.matches.create(second_accepter_id: pair_to_match.id)
    match.remove_from_potential_pairing
  end

  def remove_from_potential_pairing
    first_sequence = first_accepter.potential_pairs.where(requested_id: secondary_accepter.id).first
    second_sequence = secondary_accepter.potential_pairs.where(requested_id: first_accepter.id).first
    PotentialPair.delete([first_sequence.id, second_sequence.id])
  end
end

app/models/potential_pair.rb
class PotentialPair < ActiveRecord::Base
  belongs_to :requester, class_name: :User, foreign_key: "requester_id"
  belongs_to :requested, class_name: :User, foreign_key: "requested_id"

  def already_requested?
    accepted == true
  end

  def self.next(current_user)
    requested_pairs   = where(["requested_id = ? and accepted = ? ", current_user.id, true])
    unrequested_pairs = where(["requester_id = ? and accepted = ? ", current_user.id, false])
    (requested_pairs  + unrequested_pairs).first
  end

end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :user_languages
  has_many :languages, through: :user_languages
  has_many :potential_pairs, class_name: :PotentialPair, foreign_key: "requester_id"
  has_many :matches, class_name: :Match, foreign_key: "first_accepter_id"

  def self.find_or_create_from_auth(data)
    user = User.find_or_create_by(provider: data.provider, uid: data.uid)

    user.username  = data.info.nickname
    user.email     = data.info.email
    user.image_url = data.info.image
    user.token     = data.credentials.token
    user.save

    update_all_potential_pairs(user)
    user
  end

  def self.update_all_potential_pairs(user)
    users = User.where.not(id: user.id)
    users.map do |other_user|
      user.potential_pairs.find_or_create_by(requested_id: other_user.id)
    end
  end

  def add_preferred_languages(chosen_languages)
    chosen_languages.each do |language|
      lang_id = Language.find_by(title: language)
      user_languages.create!(language_id: lang_id.id)
    end
  end
end

app/models/user_language.rb
class UserLanguage < ActiveRecord::Base
  belongs_to :language
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user, :is_authorized?, :pair_counter

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def is_authorized?(id)
    current_user && current_user.id.to_s == (params[:id])
  end

end

app/controllers/potential_pairs_controller.rb
class PotentialPairsController < ApplicationController

  def index
    @potential_pair = PotentialPair.next(current_user)
    if @potential_pair
      if @potential_pair.requested_id == current_user.id
        @pair = User.find(@potential_pair.requester_id)
      else
        @pair = User.find(@potential_pair.requested_id)
      end
    else
      redirect_to root_path
      flash[:notice] = "you have no more suggested pairs at this time"
    end
  end

  def create
  end

  def update
    ppair = current_user.potential_pairs.find_by(requested_id: params[:potential].keys.first)
    if ppair.already_requested?
      pair = User.find(ppair.requested_id)
      Match.make(current_user, pair)
      redirect_to user_potential_pairs_path(current_user)
      flash[:notice] = "Congratulations " + current_user.username + ", you are a match with " + pair.username
    else
      ppair.update_attributes!(accepted: true)
      redirect_to user_potential_pairs_path(current_user)
      flash[:notice] = "Request Saved"
    end
  end

  def remove
    ppair = current_user.potential_pairs.find_by(requested_id: params[:potential].keys.first)
    current_user.potential_pairs.delete(ppair.id)
    redirect_to user_potential_pairs_path(current_user)
    flash[:notice] = "Rejection saved, Ouch!"
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.find_or_create_from_auth(request.env["omniauth.auth"])
    if user
      session[:user_id] = user.id
      if user.user_languages.empty?
        redirect_to edit_user_path(user)
      else
        redirect_to root_path
      end
    else
      flash[:error] = "something went wrong"
      redirect_to :back
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "You have been logged out"
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :user

  def show
    if is_authorized?(user.id)
      redirect_to root_path
    else
      redirect_to root_path
      flash[:error] = "Not Authorized"
    end
  end

  def edit
    @languages = Language.all
  end

  def update
    user.update_attributes!(about: params[:user][:about])
    user.add_preferred_languages(params[:language].keys)
    if user.save
      redirect_to  root_path(user)
    else
      redirect_to :back
      flash[:error] = "something went wrong"
    end
  end

  private

  def user
    @user = User.find(params[:id])
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="pairr navbar-brand" href="/">Pairr</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if current_user %>
          <li><%= link_to "logout", logout_path, method: :delete, class: "navi-btn" %></li>
        <% else %>
          <li><%= link_to "login with GitHub", "/auth/github", class: "navi-btn" %></li>
        <% end %>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li id="slogan">Your pair is a click away</li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FinalAssessment</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="container">

      <%= render partial: "layouts/navbar" %>

      <div class="messsages">
        <% flash.each do |name, msg| %>
          <%= content_tag :div, msg, id: "flash_#{name}" %>
        <% end %>
      </div>

      <%= yield %>
    </div>
  </body>
</html>

app/views/potential_pairs/index.html.erb
<h3>Find Your Next Pair!</h3>

<div>
  <h3><%= @pair.username.capitalize %></h3>
  <p><%= @pair.about %></p>
  <img src="<%= @pair.image_url %>"</img>
  <ul><h3>languages I prefer:</h3>
    <% @pair.languages.each do |language| %>
      <li><%= language.title %></li>
      <% end %>
  </ul>

  <div id="reject-form">
  <%= form_for :potential_pairs, url: user_potential_pairs_remove_path(user_id: current_user.id), html: {method: :delete} do |f| %>
    <input type="hidden" name="potential[<%= @pair.id %>]">
    <%= f.submit "Reject" %>
  <% end %>
  </div>

  <div id="accept-form">
  <%= form_for :potential_pairs, url: user_potential_pair_path(user_id: current_user.id, id: @potential_pair.id ), html: {method: :put} do |f| %>
    <input type="hidden" name="potential[<%= @pair.id %>]">
    <%= f.submit "Approve" %>
  <% end %>
  </div>

</div>

app/views/shared/_user_matches.html.erb
<div class="row">
<div class="col-sm-4">
  <ul>You are matched with:
    <% current_user.matches.each do |match| %>
      <% if current_user == match.first_accepter %>
        <li><%= match.secondary_accepter.username %></li>
      <% else %>
        <li><%= match.first_accepter.username %></li>
      <% end %>
    <% end %>
  </ul>
</div>
</div>

app/views/users/edit.html.erb
<h2>About You</h2>
<%= form_for @user, url: user_path(@user.id) do |f| %>
  <div class="form-group">
    <p>Tell Us About Yourself</p>
    <%= f.text_area :about, :maxlength => 500, placeholder: "What are you looking for in a pair...." %>
  </div>
  <div class="form-group">
    <p>What Are Your Preffered Programming Languages?</p>
    <% @languages.each do |language| %>
      <%= f.label language.title %>
      <input type="checkbox" id="<%= language.title %>" name="language[<%= language.title %>]">
    <% end %>
    <div class="form-group">
      <%= f.submit "Save My Info" %>
    </div>
  </div>
<% end %>

app/views/welcome/index.html.erb
<div class="homepage">
<div class="row">

<% if current_user %>
  <div class="span12">
    <h2><%= current_user.username.capitalize %>'s Dashboard</h2>
  </div>

  <div class="span5">
    <%= image_tag current_user.image_url %>
    <%= render partial: "shared/user_matches" %>
  </div>

  <h3><%= link_to "Find Pairs", user_potential_pairs_path(user_id: current_user.id) %></h3>
<% else %>
  <div class="span10">
    <h1 class="border col-sm-10 col-sm-offset-1"><%= link_to "Login With GitHub", "/auth/github" %></h1>
  </div>
<% end %>
</div>
</div>